// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIVJS8ddP8_iryGTmmYIyDKsoDPMuQX0',
    appId: '1:103906981915:web:c7120a5f0731d3a19660be',
    messagingSenderId: '103906981915',
    projectId: 'ecommerce-app-cb4b2',
    authDomain: 'ecommerce-app-cb4b2.firebaseapp.com',
    storageBucket: 'ecommerce-app-cb4b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDwnG5hLWcTQp56RzpV3R-BbmdISYfqFI',
    appId: '1:103906981915:android:22af0c5d95f026879660be',
    messagingSenderId: '103906981915',
    projectId: 'ecommerce-app-cb4b2',
    storageBucket: 'ecommerce-app-cb4b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQAKdvrHuKI5cWM_UhipQ-VK4yGGXrZo',
    appId: '1:103906981915:ios:e43f9609f13faecf9660be',
    messagingSenderId: '103906981915',
    projectId: 'ecommerce-app-cb4b2',
    storageBucket: 'ecommerce-app-cb4b2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQAKdvrHuKI5cWM_UhipQ-VK4yGGXrZo',
    appId: '1:103906981915:ios:e43f9609f13faecf9660be',
    messagingSenderId: '103906981915',
    projectId: 'ecommerce-app-cb4b2',
    storageBucket: 'ecommerce-app-cb4b2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXIVJS8ddP8_iryGTmmYIyDKsoDPMuQX0',
    appId: '1:103906981915:web:35dc885fb7e2bb439660be',
    messagingSenderId: '103906981915',
    projectId: 'ecommerce-app-cb4b2',
    authDomain: 'ecommerce-app-cb4b2.firebaseapp.com',
    storageBucket: 'ecommerce-app-cb4b2.firebasestorage.app',
  );
}
